

spring:
  application:
    name: Webservice11Application
  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

healthcheck:
  enabled: true

server:
  port: 8761